#!/bin/bash
sudo apt-get update
sudo apt-get -y upgrade 
sudo echo "Install git..."
sudo apt-get -y install git-core
sudo echo "Download WiringPi..."
git clone git://git.drogon.net/wiringPi
sudo echo "Install WiringPi..."
cd ~/wiringPi
./build
cd
sudo echo "WiringPi was installed!"
sudo echo "Download audio configuration files..."
git clone https://github.com/Madeski/raspberry.git
cd ~/raspberry
sudo echo "Configurate alt mode for pins!"
gcc -o gpio_alt gpio_alt.c
sudo chown root:root gpio_alt
sudo chmod u+s gpio_alt
sudo mv gpio_alt usr/local/bin/
gpio_alt -p 13 -f 0
gpio_alt -p 18 -f 5
sudo echo "Lets force 3.5mm audio"
amixer cset numid=3 "1"
sudo echo "Setup pwmausio..."                                   
sudo chmod +x /root/pwmaudio.sh
sudo systemctl enable pwmaudio.service 
sudo systemctl start pwmaudio.service
sudo echo "Ready!"
cd
sudo apt-get -y install mpg123
#sudo reboot
