#!/bin/bash
cd /home/pi
echo "Install git..."
apt-get -y install git-core
echo "Download WiringPi..."
git clone git://git.drogon.net/wiringPi
echo "Install WiringPi..."
cd /home/pi/wiringPi
./build
cd /home/pi
echo "WiringPi was installed!"
echo "Download audio configuration files..."
git clone https://github.com/Madeski/raspberry.git
cd /home/pi/raspberry
echo "Configurate alt mode for pins!"
gcc -o gpio_alt gpio_alt.c
chown root:root gpio_alt
chmod u+s gpio_alt
mv gpio_alt /usr/local/bin/
echo "Lets force 3.5mm audio"
amixer cset numid=3 "1"  
echo "Setup pwmaudio..."  
mv pwmaudio.sh /root                                  
chmod +x /root/pwmaudio.sh
mv pwmaudio.service /lib/systemd/system/
systemctl enable pwmaudio.service 
systemctl start pwmaudio.service
echo "Ready!"
reboot
