#!bin/bash
sudo apt-get update
sudo apt-get -y upgrade 
sudo apt-get -y install git-core
git clone git://git.drogon.net/wiringPi
cd ~/wiringPi
./build
cd
git clone git@github.com:Madeski/raspberry.git
cd raspberry
gcc -o gpio_alt gpio_alt.c
sudo chown root:root gpio_alt
sudo chmod u+s gpio_alt
sudo mv gpio_alt usr/local/bin/
gpio_alt -p 13 -f 0
gpio_alt -p 18 -f 5
amixer cset numid=3 "1"                               #force 3.5mm Jack
sudo chmod +x /root/pwmaudio.sh
sudo systemctl enable pwmaudio.service 
sudo systemctl start pwmaudio.service
sudo reboot
