#!/bin/bash
cd /etc/wpa_supplicant
echo "country=CZ
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
 ssid="Vergil Inc."
 scan_ssid=1
 psk="wifightit"
 key_mgmt=WPA-PSK
} " >> wpa_supplicant.conf
cd /boot
sudo touch ssh.txt
sudo reboot
